
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.p2ed.ReglasGram.datos;

/** CUP generated class containing symbol constants. */
public class symDatos {
  /* terminals */
  public static final int CADENA = 12;
  public static final int SALON = 6;
  public static final int SEMI = 17;
  public static final int HORARIO = 8;
  public static final int ASIGNAR = 9;
  public static final int STRING = 11;
  public static final int COMA = 16;
  public static final int EOF = 0;
  public static final int EDIFICIO = 5;
  public static final int error = 1;
  public static final int NUMERO = 15;
  public static final int USUARIO = 3;
  public static final int ESTUDIANTE = 2;
  public static final int PAI = 13;
  public static final int CATEDRATICO = 4;
  public static final int INVALID = 18;
  public static final int PAD = 14;
  public static final int COLABORADOR = 10;
  public static final int CURSO = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ESTUDIANTE",
  "USUARIO",
  "CATEDRATICO",
  "EDIFICIO",
  "SALON",
  "CURSO",
  "HORARIO",
  "ASIGNAR",
  "COLABORADOR",
  "STRING",
  "CADENA",
  "PAI",
  "PAD",
  "NUMERO",
  "COMA",
  "SEMI",
  "INVALID"
  };
}

