/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.p2ed.fronted;

import com.mycompany.p2ed.Informacion.Almacenamiento;
import com.mycompany.p2ed.objetos.Edificio;
import com.mycompany.p2ed.objetos.Salon;
import javax.swing.JOptionPane;

/**
 *
 * @author sergi
 */
public class FormSalones extends javax.swing.JFrame {

    private Salon salonMod;
    private boolean isAdd = true;
    private Almacenamiento almacenamiento;
    /**
     * Creates new form FormSalones
     */
    public FormSalones(Almacenamiento almacenamiento) {
        initComponents();
        this.almacenamiento = almacenamiento;        
    }
    
    public FormSalones(Almacenamiento almacenamiento,String id,Salon salon){
        initComponents();
        this.almacenamiento = almacenamiento;
        isAdd= false;
        txtSalon.setText(id);
        txtSalon.setEnabled(false);
        txtEdificio.setEnabled(false);
        this.salonMod = salon;
        txtEdificio.setText(salon.getEdificio().getNombre());
        txtCapacidad.setText(String.valueOf(salon.getCapacidad()));
        lblTitle.setText("Modificar Salon");
    }
    
    
    private void add(){
        try{
            String edificio = txtEdificio.getText();
            int Salon = Integer.parseInt(txtSalon.getText());
            int capacidad = Integer.parseInt(txtCapacidad.getText());
            
            Edificio edi = almacenamiento.getListEdificio().get(edificio);
            if(edi == null){
                    JOptionPane.showMessageDialog(this,"No exite el edificio: " + edificio,"error",JOptionPane.ERROR_MESSAGE); 
            } else{
                    Salon salon = new Salon(edi,Salon,capacidad);                    
                    boolean bol = edi.getSalones().push(Salon,salon);
                    if(bol==false){
                        JOptionPane.showMessageDialog(this,"Ya existe el salon: " + Salon,"error",JOptionPane.ERROR_MESSAGE);                          
                    }else{
                        JOptionPane.showMessageDialog(this,"Salon Agregado","Hecho",JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                    }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Ocurrio un error " + e.getMessage(),"error",JOptionPane.ERROR_MESSAGE); 
        }
    }
    
    private void mod(){
        try{
            String edificio = txtEdificio.getText();
            int Salon = Integer.parseInt(txtSalon.getText());
            int capacidad = Integer.parseInt(txtCapacidad.getText());            
            Edificio edi = almacenamiento.getListEdificio().get(edificio);
            if(edi == null){
                    JOptionPane.showMessageDialog(this,"No exite el edificio: " + edificio,"error",JOptionPane.ERROR_MESSAGE); 
            } else{
                    salonMod.setCapacidad(capacidad);
                    salonMod.setEdificio(edi);
                    boolean bol = edi.getSalones().Modificar(Salon, salonMod);
                    if(bol){
                        JOptionPane.showMessageDialog(this,"Salon Modificado","Hecho",JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();                                                 
                    }else{
                        JOptionPane.showMessageDialog(this,"No se encontro el salon: " + Salon,"error",JOptionPane.ERROR_MESSAGE); 
                    }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Ocurrio un error " + e.getMessage(),"error",JOptionPane.ERROR_MESSAGE); 
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCapacidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtEdificio = new javax.swing.JTextField();
        txtSalon = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtCapacidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Capacidad");

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle.setText("Crear Salon");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nombre del edificio");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtEdificio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtSalon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Numero de salon");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSalon, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(27, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (isAdd) {
            add();
        }else{
            mod();
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtEdificio;
    private javax.swing.JTextField txtSalon;
    // End of variables declaration//GEN-END:variables
}
