/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.p2ed.fronted;

import com.mycompany.p2ed.Informacion.Almacenamiento;
import com.mycompany.p2ed.Nodos.NodeHash;
import com.mycompany.p2ed.objetos.Asignar;
import com.mycompany.p2ed.objetos.Estudiante;
import com.mycompany.p2ed.objetos.Horario;
import javax.swing.JOptionPane;

/**
 *
 * @author sergi
 */
public class FormAsingnar extends javax.swing.JFrame {
    private Almacenamiento almacenamiento;
    private boolean isAdd = true;
    private Asignar asignar;
    /**
     * Creates new form FormAsingnar
     */
    public FormAsingnar(Almacenamiento almacenamiento) {
        initComponents();
        this.almacenamiento = almacenamiento;
        
    }
    public FormAsingnar(Almacenamiento almacenamiento, Asignar asignar) {
        initComponents();
        this.almacenamiento = almacenamiento;
        this.asignar = asignar;
        lblTitle.setText("Modificar Asignacion");
        txtCarnet.setText(String.valueOf(asignar.getEstudiante().getCarnet()));
        txtCodHorario.setText(String.valueOf(asignar.getHorario().getId()));
        txtCarnet.setEnabled(false);
        txtCodHorario.setEnabled(false);
        isAdd = false;
        txtFinal.setText(String.valueOf(asignar.getEx_final()));
        txtZona.setText(String.valueOf(asignar.getZona()));
    }
    
    
    private void add(){
        try{
            int Carnet = Integer.valueOf(txtCarnet.getText());//Estudiante
            int CodHorario = Integer.valueOf(txtCodHorario.getText());//Horario
            int Zona = Integer.valueOf(txtZona.getText());
            int Ex_final = Integer.valueOf(txtFinal.getText());
            Estudiante estud = almacenamiento.getHash().get(Carnet);
            NodeHash estu1 =  almacenamiento.getHash().getNode(Carnet);
            Horario horario = almacenamiento.getHorario().get(CodHorario);
            if (estud == null) {
                    JOptionPane.showMessageDialog(this,"El estudiante no existe ","error",JOptionPane.ERROR_MESSAGE);
            }else if(horario == null){
                    JOptionPane.showMessageDialog(this,"El horario no existe ","error",JOptionPane.ERROR_MESSAGE);
            }else{
                    Asignar asginar =  almacenamiento.getAsignacion().get(Carnet,CodHorario);
                    if(asginar == null){
                            asginar = new Asignar(estud,horario,Zona,Ex_final);
                            asginar.setEstudiante1(estu1);
                            almacenamiento.getAsignacion().push(Carnet,CodHorario,asginar);
                            horario.getAsignaciones().push(Carnet,CodHorario,asginar);
                            JOptionPane.showMessageDialog(this,"Asignacion Agregada","Hecho",JOptionPane.INFORMATION_MESSAGE);
                            this.dispose();
                    }else{
                            JOptionPane.showMessageDialog(this,"Ya existe una asginacion entre el horario y el estudiante ","error",JOptionPane.ERROR_MESSAGE);
                    }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Ocurrio un error " + e.getMessage(),"error",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void mod(){
        try{
            int Carnet = Integer.valueOf(txtCarnet.getText());//Estudiante
            int CodHorario = Integer.valueOf(txtCodHorario.getText());//Horario            
            int Zona = Integer.valueOf(txtZona.getText());
            int Ex_final = Integer.valueOf(txtFinal.getText());
            
            asignar.setEx_final(Ex_final);
            asignar.setZona(Zona);            
            Horario horario = almacenamiento.getHorario().get(CodHorario);
            
            boolean bol = horario.getAsignaciones().modificar(Carnet, CodHorario, asignar);
            if (bol) {
                JOptionPane.showMessageDialog(this,"Asignacion Modificada","Hecho",JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
            }else{
                JOptionPane.showMessageDialog(this,"No se encontro la asignacion: " + Carnet,"error",JOptionPane.ERROR_MESSAGE);
            }            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Ocurrio un error " + e.getMessage(),"error",JOptionPane.ERROR_MESSAGE);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtZona = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtCarnet = new javax.swing.JTextField();
        txtCodHorario = new javax.swing.JTextField();
        txtFinal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Codigo de horario");

        txtZona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Zona");

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle.setText("Crear Asignacion");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Carnet de estudiante");

        jButton3.setText("Aceptar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtCarnet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtCodHorario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtFinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Final");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(txtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtZona, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(txtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (isAdd) {
            add();
        }else{
            mod();
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCarnet;
    private javax.swing.JTextField txtCodHorario;
    private javax.swing.JTextField txtFinal;
    private javax.swing.JTextField txtZona;
    // End of variables declaration//GEN-END:variables
}
