/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.p2ed.fronted;

import com.mycompany.p2ed.CargaDatos;
import com.mycompany.p2ed.Dibujar;
import com.mycompany.p2ed.Informacion.Almacenamiento;
import com.mycompany.p2ed.Nodos.NodeCD;
import com.mycompany.p2ed.fronted.Opciones.*;
import com.mycompany.p2ed.objetos.Usuario;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.nio.charset.StandardCharsets;
import javax.swing.JOptionPane;

/**
 *
 * @author sergi
 */
public class MenuSuper extends javax.swing.JFrame {

    Almacenamiento almacenamiento;
    private Dibujar dibujar = new Dibujar();
    private FunctionsEdificio funEdificio;
    private FunctionsUsers funUser;
    private FunctionsSalones funSalon;
    /**
     * Creates new form MenuSuper
     * @param almacenamiento
     */
    public MenuSuper(Almacenamiento almacenamiento) {
        initComponents();
        this.almacenamiento = almacenamiento;
        funEdificio = new FunctionsEdificio(almacenamiento);
        funUser = new FunctionsUsers(almacenamiento,this);
        funSalon = new FunctionsSalones(almacenamiento,this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cargarDatos = new javax.swing.JMenu();
        cargaDatos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        logout = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        addUser = new javax.swing.JMenuItem();
        modUser = new javax.swing.JMenuItem();
        deleteUser = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        addEdificio = new javax.swing.JMenuItem();
        deleteEdificio = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        addSalon = new javax.swing.JMenuItem();
        modSalon = new javax.swing.JMenuItem();
        deleteSalon = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        treeCatedraticos = new javax.swing.JMenuItem();
        GraficarEdificiosSalones = new javax.swing.JMenuItem();
        verCursos = new javax.swing.JMenuItem();
        verUsuarios = new javax.swing.JMenuItem();
        verAsginaciones = new javax.swing.JMenuItem();
        verHorario = new javax.swing.JMenuItem();
        verEstudiantes = new javax.swing.JMenuItem();
        verTodo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );

        cargarDatos.setText("Opciones");

        cargaDatos.setText("CargarDatos");
        cargaDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargaDatosActionPerformed(evt);
            }
        });
        cargarDatos.add(cargaDatos);
        cargarDatos.add(jSeparator1);

        logout.setText("Cerrar Sesion");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        cargarDatos.add(logout);

        jMenuBar1.add(cargarDatos);

        jMenu1.setText("Usuarios");

        addUser.setText("Crear");
        addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserActionPerformed(evt);
            }
        });
        jMenu1.add(addUser);

        modUser.setText("Modificar");
        modUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modUserActionPerformed(evt);
            }
        });
        jMenu1.add(modUser);

        deleteUser.setText("Eliminar");
        deleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserActionPerformed(evt);
            }
        });
        jMenu1.add(deleteUser);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Edificios");

        addEdificio.setText("Crear");
        addEdificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEdificioActionPerformed(evt);
            }
        });
        jMenu5.add(addEdificio);

        deleteEdificio.setText("Eliminar");
        deleteEdificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEdificioActionPerformed(evt);
            }
        });
        jMenu5.add(deleteEdificio);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Salones");

        addSalon.setText("Crear");
        addSalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSalonActionPerformed(evt);
            }
        });
        jMenu6.add(addSalon);

        modSalon.setText("Modificar");
        modSalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modSalonActionPerformed(evt);
            }
        });
        jMenu6.add(modSalon);

        deleteSalon.setText("Eliminar");
        deleteSalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSalonActionPerformed(evt);
            }
        });
        jMenu6.add(deleteSalon);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Cursos");

        jMenuItem10.setText("Crear");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem10);

        jMenuItem11.setText("Modificar");
        jMenu7.add(jMenuItem11);

        jMenuItem12.setText("Eliminar");
        jMenu7.add(jMenuItem12);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Estudiantes");

        jMenuItem13.setText("Crear");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem13);

        jMenuItem14.setText("Modificar");
        jMenu8.add(jMenuItem14);

        jMenuItem15.setText("Eliminar");
        jMenu8.add(jMenuItem15);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("Catedraticos");

        jMenuItem16.setText("Crear");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem16);

        jMenuItem17.setText("Modificar");
        jMenu9.add(jMenuItem17);

        jMenuBar1.add(jMenu9);

        jMenu10.setText("Asignacion");

        jMenuItem19.setText("Crear");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem19);

        jMenuItem20.setText("Modificar");
        jMenu10.add(jMenuItem20);

        jMenuItem21.setText("Eliminar");
        jMenu10.add(jMenuItem21);

        jMenuBar1.add(jMenu10);

        jMenu11.setText("Horario");

        jMenuItem23.setText("Modificar");
        jMenu11.add(jMenuItem23);

        jMenuBar1.add(jMenu11);

        jMenu2.setText("Graficar");

        treeCatedraticos.setText("Ver arbol de catedraticos");
        treeCatedraticos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treeCatedraticosActionPerformed(evt);
            }
        });
        jMenu2.add(treeCatedraticos);

        GraficarEdificiosSalones.setText("ver lista de Edificios y salones");
        GraficarEdificiosSalones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraficarEdificiosSalonesActionPerformed(evt);
            }
        });
        jMenu2.add(GraficarEdificiosSalones);

        verCursos.setText("Ver Lista de cursos");
        verCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verCursosActionPerformed(evt);
            }
        });
        jMenu2.add(verCursos);

        verUsuarios.setText("Ver la lista de usuarios");
        verUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verUsuariosActionPerformed(evt);
            }
        });
        jMenu2.add(verUsuarios);

        verAsginaciones.setText("Ver las asignaciones");
        verAsginaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verAsginacionesActionPerformed(evt);
            }
        });
        jMenu2.add(verAsginaciones);

        verHorario.setText("Ver arbol de horario");
        verHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verHorarioActionPerformed(evt);
            }
        });
        jMenu2.add(verHorario);

        verEstudiantes.setText("Ver los Estudiantes");
        verEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verEstudiantesActionPerformed(evt);
            }
        });
        jMenu2.add(verEstudiantes);

        verTodo.setText("Ver Todo");
        verTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verTodoActionPerformed(evt);
            }
        });
        jMenu2.add(verTodo);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserActionPerformed
        // TODO add your handling code here:
        funUser.add();        
    }//GEN-LAST:event_addUserActionPerformed

    private void addEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEdificioActionPerformed
        // TODO add your handling code here:
        funEdificio.Add(this);
    }//GEN-LAST:event_addEdificioActionPerformed

    private void addSalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSalonActionPerformed
        // TODO add your handling code here:
        funSalon.add();
    }//GEN-LAST:event_addSalonActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void verAsginacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verAsginacionesActionPerformed
        // TODO add your handling code here:
        dibujar.estrucGeneric(almacenamiento.getEstadoAsignaciones(),"Asginaciones");
    }//GEN-LAST:event_verAsginacionesActionPerformed

    private void verTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verTodoActionPerformed
        // Ver todo
        dibujar.estrucGeneric(almacenamiento.getEstadoTodo(), "TODO");
    }//GEN-LAST:event_verTodoActionPerformed

    private void cargaDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargaDatosActionPerformed
        // TODO add your handling code here:
        CargaDatos cargar =  new CargaDatos();
        File file = cargar.getFile();
        if (file != null) {
            almacenamiento.cargarDatos(converterBuffer(file));
        }        
    }//GEN-LAST:event_cargaDatosActionPerformed

    private void verEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verEstudiantesActionPerformed
        // TODO add your handling code here:
        dibujar.hash(almacenamiento.getEstadoEstudiantes(), "Hash");
    }//GEN-LAST:event_verEstudiantesActionPerformed

    private void verHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verHorarioActionPerformed
        // TODO add your handling code here:
        dibujar.estrucGeneric(almacenamiento.getEstadoHorario(), "TreeHorario");
    }//GEN-LAST:event_verHorarioActionPerformed

    private void verUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verUsuariosActionPerformed
        // TODO add your handling code here:
        dibujar.estrucGeneric(almacenamiento.getEstadoUsuarios(),"ListUsuarios");
    }//GEN-LAST:event_verUsuariosActionPerformed

    private void verCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verCursosActionPerformed
        // TODO add your handling code here:
        dibujar.estrucGeneric(almacenamiento.getEstadoCursos(),"ListCursos");
    }//GEN-LAST:event_verCursosActionPerformed

    private void GraficarEdificiosSalonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraficarEdificiosSalonesActionPerformed
        // TODO add your handling code here:
        dibujar.estrucGeneric(almacenamiento.getEstadoEdificios(),"ListEdificos");
    }//GEN-LAST:event_GraficarEdificiosSalonesActionPerformed

    private void treeCatedraticosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treeCatedraticosActionPerformed
        // TODO add your handling code here:        
        dibujar.avlCatedraticos(almacenamiento.getEstadoCatedraticos());
    }//GEN-LAST:event_treeCatedraticosActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        Login login = new Login(almacenamiento);
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_logoutActionPerformed

    private void deleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserActionPerformed
        // TODO add your handling code here:
        funUser.delete();
    }//GEN-LAST:event_deleteUserActionPerformed

    private void modUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modUserActionPerformed
        // TODO add your handling code here:
        funUser.mod();
    }//GEN-LAST:event_modUserActionPerformed

    private void deleteEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEdificioActionPerformed
        // TODO add your handling code here:
        funEdificio.eliminar(this);
    }//GEN-LAST:event_deleteEdificioActionPerformed

    private void modSalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modSalonActionPerformed
        // TODO add your handling code here:
        funSalon.mod();
    }//GEN-LAST:event_modSalonActionPerformed

    private void deleteSalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSalonActionPerformed
        // TODO add your handling code here:
        funSalon.delete();
    }//GEN-LAST:event_deleteSalonActionPerformed

    private static BufferedReader converterBuffer(File file){
        try{
            BufferedReader br = new BufferedReader(new FileReader(file,StandardCharsets.UTF_8));
            return br;
        }catch(Exception e){            
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem GraficarEdificiosSalones;
    private javax.swing.JMenuItem addEdificio;
    private javax.swing.JMenuItem addSalon;
    private javax.swing.JMenuItem addUser;
    private javax.swing.JMenuItem cargaDatos;
    private javax.swing.JMenu cargarDatos;
    private javax.swing.JMenuItem deleteEdificio;
    private javax.swing.JMenuItem deleteSalon;
    private javax.swing.JMenuItem deleteUser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenuItem modSalon;
    private javax.swing.JMenuItem modUser;
    private javax.swing.JMenuItem treeCatedraticos;
    private javax.swing.JMenuItem verAsginaciones;
    private javax.swing.JMenuItem verCursos;
    private javax.swing.JMenuItem verEstudiantes;
    private javax.swing.JMenuItem verHorario;
    private javax.swing.JMenuItem verTodo;
    private javax.swing.JMenuItem verUsuarios;
    // End of variables declaration//GEN-END:variables
}
